[commands]
predev = "npx prisma generate"
dev = "npx prisma migrate deploy && npm exec react-router dev"

name = "react-router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"
